name: .NET CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  style:
    name: Code style (quiet verify)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            6.0.x

      # Enforce only auto-fixable formatting/styles. Quiet unless failures.
      - name: Verify style formatting
        run: dotnet format style --verify-no-changes --verbosity minimal

      - name: Verify whitespace formatting
        run: dotnet format whitespace --verify-no-changes --verbosity minimal

      # Include fixable analyzer diagnostics.
      - name: Verify fixable analyzers (usings)
        run: dotnet format analyzers --diagnostics IDE0005,IDE0065 --verify-no-changes --verbosity minimal

  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: style
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            6.0.x
          cache: true
          cache-dependency-path: |
            **/packages.lock.json
            global.json
            **/*.csproj
            Directory.Build.props

      - name: Restore (locked mode)
        run: dotnet restore --locked-mode

      # Enforce naming conventions via build.
      - name: Build (naming enforced)
        run: dotnet build --configuration Release --no-restore -warnaserror:IDE1006

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
